language: cpp
sudo: required
services: docker

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - python-openssl

before_script:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 99
  - sudo -E add-apt-repository -y 'deb http://ftp.us.debian.org/debian unstable main contrib non-free'
  - sudo apt-get update -qq
  - sudo apt-get install -y --force-yes python-boto3

script:
  - ./autogen.sh
  - ./configure
  - make -j3 distcheck

after_failure:
  - cat mu-0.01/_build/src/tests/test-suite.log

notifications:
  slack: keithw:bq7WABbx9cSlgMM8vljjOPh5
